project:
  type: book

book:
  title: "Life Skills and Hobbies"
  author: "Igor Dimitrov"
  date: "5/17/2024"
  chapters:
    - index.qmd
    - 3-week-meal-plan.qmd
  page-navigation: true

# bibliography: references.bib

number-depth: 1

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



